### ISSUE TITLE
Fix flake8

### ISSUE THREAD

**Issue by IKostric** [iai-group/MovieBot#102]
Allow for some `# noqa`, specifically for complex functions/methods before we refactor those.

**Comment by NoB0** [comment]
Maybe `dialogue_state_tracker` property in `DialogueManager` could be renamed `dst` to solve a lot of E501 errors. What do you think?

**Comment by IKostric** [comment]
My idea was to abstract away `dialogue_state_tracker` and have getters and setters on `DialogueManager` for it instead of it being directly accessed by other modules. This would align the architecture with the figure [here](https://iai-moviebot.readthedocs.io/en/latest/architecture.html).
