### ISSUE TITLE
Refactor complex methods

### ISSUE THREAD

**Issue by NoB0** [iai-group/MovieBot#107]
The following methods are too complex and need to be refactored:
- [ ] `NLG.generate_output`
 `NLG._clarify_CIN`
- [ ] `NLG._user_options_remove_preference`
- [ ] `NLG._user_options_remove_preference_CIN`
- [ ] `UserIntentsChecker._filter_dact`
- [x] `DataLoader.load_database`
- [ ] `NLU.generate_dact`
- [x] `RBAnnotator._year_annotator`
- [x] `DialoguePolicy.next_action`
- [ ] `DialogueStateTracker.update_state_user`
- [x] `Agent.initialize`

**Comment by kbalog** [comment]
The remaining ones will be part of v2 (a new issue is to be created for them).

**Comment by IKostric** [comment]
I have created a new issue for the remaining complex methods.
