### ISSUE TITLE
Remove `initialize` and `_add_year_CIN` methods in DialogueStateTracker?

### ISSUE THREAD

**Issue by NoB0** [iai-group/MovieBot#109]
The method [initialize](https://github.com/iai-group/MovieBot/blob/23dcb4e37ec633de6dfb67b2feecacbb7c4e37f6/moviebot/dialogue_manager/dialogue_state_tracker.py#L35) in DialogueStateTracker is defined but not implemented.

It appears that both methods (`initialize` and `_add_year_CIN`) are unused, should we remove it?

**Comment by IKostric** [comment]
I would say yes. Less clutter == better.
