### ISSUE TITLE
A failure in launching flask server

### ISSUE THREAD

**Issue by LuJiayi1008** [iai-group/MovieBot#150]
Sorry to disturb you, but I encountered a problem when launching the flask server of IAI MovieBot.
I modified the import section in run.py and its related parts as well:
from moviebot.controller import server_rest
and run 'python -m  moviebot.run -c config/moviebot_config_no_integration.yaml' in terminal.
Here is what I get in terminal:
2023-03-23 01:50:39,254 - root - INFO - Configuration file "config/moviebot_config_no_integration.yaml" is loaded.
 * Serving Flask app 'moviebot.controller.server_rest' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-03-23 01:50:39,321 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-03-23 01:50:39,333 - werkzeug - INFO -  * Running on http://26.26.26.1:5001/ (Press CTRL+C to quit)

when I turn to http://26.26.26.1:5001/ I only got a sentense 'MovieBot is alive' and nothing else. I don't know how to use it.
I am really upset and clueless about this result. I would appreciate it very much if you could offer me some guidance.

**Comment by NoB0** [comment]
We do not have a web client for MovieBot when it is deployed using a Flask REST server. Therefore, accessing  http://26.26.26.1:5001/ only confirms that the Flask server is up and running. 
Some changes have been made to the code and it is now possible to deploy the MovieBot as a Flask socket.io server and connect it to a [web client](https://www.npmjs.com/package/iaigroup-chatwidget). To do so please follow the instructions below:
- Pull the last version of the branch `main` 
- Run `python -m moviebot.run -c config/moviebot_config_no_integration.yaml`
- Create an HTML file as follow for the web client

```html
<!DOCTYPE html>
<html>
<head>
    <title>MovieBot</title>
</head>
<body>
    <script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/iaigroup-chatwidget@1.1.2/build/bundle.min.js"></script>
    <script type="text/javascript">
        ChatWidget({
            name: "MovieBot",
            serverUrl: "http://127.0.0.1:5001",
            socketioPath: "/socket.io/",
            useFeedback: false,
            useLogin: false,
        });
    </script>
</body>

</html>
```

- Open the HTML file in your web browser. A button to discuss with MovieBot should be placed at the bottom right.

Thanks for pointing this out, we will work on improving the usage documentation.
