### ISSUE TITLE
Option to run MovieBot as a Flask server without integrations.

### ISSUE THREAD

**Issue by adrzewiecki** [iai-group/MovieBot#44]
## The problem

The current implementation does not allow for MovieBot to only run as a RESTful server.
This would make it possible and easier for other services to talk to the bot.

## Proposed solution

Have a REST API that uses the response as the bot response utterance. Without any 3rd party integration.

**Comment by kbalog** [comment]
@IKostric What do you think about this?

**Comment by IKostric** [comment]
This could be relevant for the web chat interface. Another approach would be to use Web Sockets.

**Comment by kbalog** [comment]
@IKostric I like that proposal as that'd allow us to use Flask (which is our default solution for web-facing stuff)
